# Generated by Django 5.1.14 on 2026-08-27 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("frame_count", models.PositiveIntegerField(default=0)),
                ("box_count", models.PositiveIntegerField(default=0)),
                ("confidence_sum", models.FloatField(default=0)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detection_metrics",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "db_table": "detection_metrics",
                "ordering": ["-date"],
                "unique_together": {("date", "camera")},
            },
        ),
    ]
