# Generated by Django 5.1.14 on 2026-08-27 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("intrusion", "区域入侵"),
                            ("parking", "违停占道"),
                            ("fire", "火灾隐患"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("high", "高危"), ("medium", "中危"), ("low", "低危")],
                        default="medium",
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("confidence", models.FloatField(default=0.8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unhandled", "待处理"),
                            ("processing", "处理中"),
                            ("resolved", "已处理"),
                        ],
                        default="unhandled",
                        max_length=16,
                    ),
                ),
                (
                    "snapshot_url",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("image_url", models.CharField(blank=True, default="", max_length=255)),
                ("video_url", models.CharField(blank=True, default="", max_length=255)),
                ("detection_boxes", models.JSONField(default=list)),
                ("triggered_at", models.DateTimeField()),
                (
                    "resolved_by",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "db_table": "alerts",
                "ordering": ["-triggered_at"],
            },
        ),
    ]
