# Generated by Django 5.1.14 on 2026-09-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlywheelSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_id", models.IntegerField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("alert", "告警帧"), ("uncertain", "不确定帧")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("alert_id", models.IntegerField(blank=True, null=True)),
                ("stem", models.CharField(max_length=128, unique=True)),
                ("image_key", models.CharField(max_length=255)),
                ("label_key", models.CharField(max_length=255)),
                ("max_conf", models.FloatField(default=0)),
                ("box_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "flywheel_samples",
                "ordering": ["-id"],
            },
        ),
    ]
