# Generated by Django 5.1.14 on 2026-08-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(blank=True, default="", max_length=128)),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("rtsp", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("hikvision", "海康威视"),
                            ("dahua", "大华"),
                            ("other", "其他"),
                        ],
                        default="hikvision",
                        max_length=32,
                    ),
                ),
                (
                    "username",
                    models.CharField(blank=True, default="admin", max_length=64),
                ),
                ("password", models.CharField(blank=True, default="", max_length=128)),
                ("resolution", models.CharField(default="1920x1080", max_length=32)),
                ("channels", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[("online", "在线"), ("offline", "离线")],
                        default="online",
                        max_length=16,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("detection_types", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cameras",
                "ordering": ["-id"],
            },
        ),
    ]
